### ISSUE TITLE
modularization

### ISSUE THREAD

**Issue by rriehle** [UWPCE-PythonCert/PythonCertDevel#15] opened 2017-10-29 14:14 UTC
My attempt at the modularization of the curriculum seems to have fallen to the wayside. This makes me sad. For a model see the abandoned [Py100](https://github.com/UWPCE-PythonCert/Py100) and [Py300](https://github.com/UWPCE-PythonCert/Py300) repos. My intent was multifaceted:

1.  to facilitate the ongoing development and enhancement of individual topics
2.  to allow stale topics to be seamlessly dropped from the curriculum as the language and its tools evolve
3.  to acknowledge each class and cohort as an organic entity with its unique needs and interests
4.  to enable adaptation around abrupt staff changes, as when an instructor or teaching assistant leaves or joins a class in mid-sequence

There are two influences running counter to the goals above:

1.  the Career Accelerator curriculum redevelopment effort which seems to demand that every class be run in lock-step like every other class
2.  the inertia of the existing non-modular curriculum materials

Should I give up on modularization?

**Comment by PythonCHB** [comment] 2017-10-29 15:27
I think we're keeping it fully modular, the Py100 and Py300 repos were merged into the PythonCertDevel repo, rather than abandoned. This made it easier to work on development of the Program  (or at least the first two quarters) as a whole.

That being said, yes, the Career Accelerator Curriculum  is, by design (and fiat) fixed. So we're not going to be able be flexible with the curriculum anymore.

I suppose that we could keep a number of "optional" modules around for the second half of the second quarter.

Also -- this stuff is all open-source, so we could use the materials for other things.

One last point, which I've tried to make a couple times:

They want to give the course in multiple "modalities" and multiple instructors -- so it makes sense to me that each instance of the class would essentially have its own syllabus that would have a pile of pointers to the modules.

The other trick to the modularization is that while some of the exercises are directly linked to a particular topic(module), the large exercises are, by their nature cross-modular.

**Closed** 2017-11-28 20:31 UTC
Labels: question
