### ISSUE TITLE
solutions directory needs attention

### ISSUE THREAD

**Issue by codedragon** [UWPCE-PythonCert/PythonCertDevel#120] opened 2018-04-15 04:29 UTC
The solutions in the Lesson directories are updated solutions. Any other solutions in the solutions directory may be outdated copies of the same exercises. We should go through the solutions in the main directory, and if they are not already in their proper lesson, put them there. If they are a duplicate or outdated, delete them.

**Comment by PythonCHB** [comment] 2018-04-16 03:01
To some extent, it's up the the individual course instructors to decide what they want to do with the solutions.

But yes, some cleanup in order --thanks for what you've done so far!

**Comment by PythonCHB** [comment] 2018-08-29 07:40
duplicate of #77

**Closed by PythonCHB** 2018-08-29 07:40 UTC
